language: objective-c
osx_image: xcode10.3

script:
    - xcodebuild clean test -project MealTracker.xcodeproj -scheme MealTracker -destination "platform=iOS Simulator,name=iPhone Xs,OS=12.4" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet