language: objective-c

xcode_workspace: MealTracker
xcode_scheme: MealTrackerTests
xcode_sdk: iphonesimulator10.0
osx_image: xcode8.3

branches:
  only:
    - master

before_install:
  - pod repo update

script:
  - xcodebuild -workspace {name}.xcworkspace -scheme {name} -sdk iphonesimulator ONLY_ACTIVE_ARCH=no
  - xcodebuild test -workspace {name}.xcworkspace -scheme {name}Tests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone 6s Plus,OS=10.0'